name: Continuous ML Pipeline (MLOps)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Unit Tests
      run: |
        python -m pytest tests/
        
    - name: Train Model & Generate Reports
      run: |
        python src/train.py
        
    - name: Write Metrics to Job Summary
      run: |
        cat reports/metrics.md >> $GITHUB_STEP_SUMMARY
        
    - name: Upload Confusion Matrix Artifact
      uses: actions/upload-artifact@v4
      with:
        name: confusion-matrix
        path: reports/confusion_matrix.png
        
    # Optional: Automatically commit the updated model and reports back to the repository
    # - name: Commit new model and metrics
    #   uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #     commit_message: "🤖 Automated ML Training: Updated Model and Metrics"
    #     file_pattern: 'models/* reports/*'
